### PR TITLE
Add k8s config

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Comment by aaron0browne** [comment]
Looks great, do you want to add a postgres container?

**Comment by bruth** [comment]
I did have the general question of where we want to host the postgres database. For now I simply added another database within the Arcus CAS service database provisioned on AWS (since it already existed). We could create a new DB on GCP.

@willstruebing Any preference for this? Ideally we wouldn't host this on k8s ourselves since a managed service exists for Postgres.

**Comment by aaron0browne** [comment]
The AWS db is fine with me for now.

**Comment by bruth** [comment]
Ok. We will go with that until we decide otherwise.

With that said, I have omitted the [config and secret configs](https://github.com/arcus/eventual/pull/20/files#diff-f450e86e41f6eb028991798707441798R44) from the repo.

**Pull request merged**
